version: "3.9"

services:
  web:
    build: .
    command: >
      sh -c "python ./url_shortener/manage.py migrate && python ./url_shortener/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
