# Generated by Django 4.0.3 on 2022-03-05 03:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('shortcode', models.CharField(max_length=64)),
                ('fullname', models.CharField(max_length=2048)),
                ('name', models.CharField(max_length=512)),
                ('query_params', models.CharField(max_length=1536, null=True)),
                ('expiration', models.DateField(default=datetime.date(2022, 3, 15))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['shortcode'], name='shortcode_u_shortco_64c980_idx'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shortcode.url'),
        ),
    ]
