# Generated by Django 4.0.3 on 2022-03-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['fullname'], name='shortcode_u_fullnam_c438b1_idx'),
        ),
    ]
