# Generated by Django 4.0.3 on 2022-03-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0002_url_shortcode_u_fullnam_c438b1_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortcode',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
